keypairs:
  auth-key:
    private-key: classpath:auth-key-pair/private.pem
    public-key: classpath:auth-key-pair/public.pem
  client-key:
    private-key: classpath:client-key-pair/private.pem
    public-key: classpath:client-key-pair/public.pem
  
